In [1]:
# Creating NumPy Arrays
import numpy as np
a = np.array([2,3,4])
print(a)


[2 3 4]


In [2]:
# Creating NumPy Arrays with start,end,step
a = np.arange(1,12,2)
print(a)

[ 1  3  5  7  9 11]


In [3]:
# Creating NumPy Array with start,end,elements to see and are evenly spaced
a = np.linspace(1,12,6)
print(a)

[ 1.   3.2  5.4  7.6  9.8 12. ]


In [4]:
# Creating NumPy Array with start,end,elements to see and are evenly spaced
a = np.linspace(1,7,4)
print(a)

[1. 3. 5. 7.]


In [5]:
# Creating NumPy Array with start,end,elements to see and are evenly spaced
a = np.linspace(1,7.5,4)
print(a)

[1.         3.16666667 5.33333333 7.5       ]


In [14]:
# Creating NumPy Array with start,end,elements to see and are evenly spaced
a = np.linspace(1,12,6)
# Reshape 1-D Array into a 2-D Array
a = a.reshape(3,2)
print(a)

[[ 1.   3.2]
 [ 5.4  7.6]
 [ 9.8 12. ]]


In [9]:
# Size of 2-D Array
a.size


6

In [10]:
# Dimensions of 2-D Array
a.shape


(3, 2)

In [15]:
# Data type of 2-D Array
a.dtype

dtype('float64')

In [16]:
# Memorize each element of array takes up
a.itemsize

8

In [19]:
# Need square brackets when declaring arrays
b = np.array([(1.5,2,3),(4,5,6)])
print(b)
#b = np.array(1,2,3) --> does not work


[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [20]:
# Arrays print boolean values when comparing to a number
print(a<4)

[[ True  True]
 [False False]
 [False False]]


In [24]:
# Can multiply all elements by a constant at once
print(a*3)
# But original array will still be unchanged
print(a)
# Need to set original array equals for it to change
a *= 3
print(a)

[[  9.   28.8]
 [ 48.6  68.4]
 [ 88.2 108. ]]
[[ 3.   9.6]
 [16.2 22.8]
 [29.4 36. ]]
[[  9.   28.8]
 [ 48.6  68.4]
 [ 88.2 108. ]]


In [25]:
# Creating an empty 2-D array full of zeros
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
# Creating an empty 2-D array full of ones
a = np.ones((2,3))
print(a)
# Creating an empty 1-D array full of ones
a = np.ones(10)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
# Creating array with specific data type
a = np.array([2,3,4], dtype = np.int16)
print(a)
# Checking type
print(a.dtype)
# Checking number of bytes
a.itemsize

[2 3 4]
int16


2

In [38]:
# Creating a random array
a = np.random.random((2,3))
print(a)

[[0.87 0.89 0.27]
 [0.61 0.21 0.34]]


In [37]:
# Setting all arrays to round to 2 decimals and whether to print zeros
np.set_printoptions(precision=2,suppress=True)
print(a)

[[0.66 0.09 0.44]
 [0.74 0.16 0.23]]


In [39]:
# Creating an array with random numbers from sepcified interval & number of elements
a = np.random.randint(0,10,5)
print(a)
# Max of a
print(a.max())
# Min of a
print(a.min())
# Sum of a
print(a.sum())
# Mean of a
print(a.mean())
# Variance of a
print(a.var())
# Standard Deviation of a
print (a.std())


[2 0 1 4 4]


In [44]:
a = np.random.randint(1,10,6)
a = a.reshape(3,2)
print(a)
# Summing all horizontal number
print(a.sum(axis=1))
# Summing all vertical numbers
print(a.sum(axis=0))



[[4 9]
 [1 8]
 [7 8]]
[13  9 15]
[12 25]


In [47]:
#Importing CSV file
data = np.loadtxt("data.csv", dtype=np.uint8, delimiter = ",",skiprows = 1)
data

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]], dtype=uint8)

In [49]:
a = np.arange(10)
#Shuffle elements in array
np.random.shuffle(a)
print(a)
#Choose a random element in array 
np.random.choice(a)


[5 4 0 2 9 8 7 6 1 3]


2

In [51]:
#Choosing random integers from specified interval
np.random.random_integers(5,11,2)


/Users/Jessica/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(5, 11 + 1) instead
  


array([7, 7])